# Generated by Django 4.1.4 on 2022-12-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_user_email_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
