# Generated by Django 4.1.4 on 2022-12-21 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_remove_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("songId", models.CharField(max_length=10, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=50)),
                ("genres", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("user", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
