# Generated by Django 4.1.4 on 2022-12-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_likedsongs"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LikedSongs",
            new_name="LikedSong",
        ),
    ]
