# Generated by Django 4.1.4 on 2022-12-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPreference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='genres',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
