# Generated by Django 4.1.4 on 2022-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userInfo', '0002_favorite_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='song',
        ),
        migrations.AddField(
            model_name='favorite',
            name='song',
            field=models.ManyToManyField(to='userInfo.song'),
        ),
    ]
