# Generated by Django 4.1.4 on 2022-12-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.TextField(choices=[('HN', 'Hindi'), ('EN', 'English')])),
                ('genres', models.TextField(max_length=100)),
            ],
        ),
    ]
