# Generated by Django 4.1.4 on 2022-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='genres',
            field=models.TextField(choices=[('POP', 'Pop'), ('LATIN', 'Latin'), ('EDM', 'Edm')]),
        ),
    ]
