# Generated by Django 4.1.4 on 2022-12-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPreferences', '0002_alter_userpreference_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='genres',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='languages',
            field=models.JSONField(),
        ),
    ]
